[profile.default]
src = 'src'
out = 'out'
remappings = [
    '@chainlink/contracts/=lib/chainlink/contracts',
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]
solc = '0.8.20'
evm_version = 'paris'

[rpc_endpoints]
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
